export const QueriesKey = {
	POST: 'post',
	USER_LIST: 'user-list',
	SITE_SETTINGS: 'site-settings',
	SITE_SETTINGS_GET: 'site-settings-get',
	CATEGORIES: 'categories',
	CATEGORY: 'category',
	DEPARTMENT_CREATE: 'department-create',
	DEPARTMENT_GET: 'department-get',
	DEPARTMENT_DELETE: 'department-delete',
	DESIGNATION_CREATE: 'designation-create',
	DESIGNATION_GET: 'designation-get',
	DESIGNATION_DELETE: 'designation-delete',
	EMPLOYEE: 'employee',
	EMPLOYEES: 'employees',
	EMPLOYEE_PROFILE: 'employee-profile',
	EMPLOYEE_UPDATE: 'employee-update',
	EMPLOYEE_DELETE: 'employee-delete',
};
